# Usamos una imagen oficial de Node.js
FROM node:22-alpine

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos de dependencias primero
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código del backend
COPY . .

# Exponemos el puerto que usa nuestro servidor Express
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]